name: Laravel CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
    laravel-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup PHp environmet
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.4'
                extensions: mbstring, dom, fileinfo, mysql
                coverage: none
            - name: Copy .env file
              run: php -r "file_exists('.env') || copy('.env.example', '.env');"
            - name: Install dependencies
              run: composer install -q --no-progress --prefer-dist --optimize-autoloader
            - name: Generate Key
              run: php artisan key:generate
            - name: Create Database
              run: |
                mkdir -p dataabase
                touch database/database.sqlite
            - name: Run Migrations
              env:
                DB_CONNECTION: sqlite
                DB_DATABASE: database/database.sqlite
              run: php artisan migrate
            - name: Execute tests (PHPUnit)
              env:
                DB_CONNECTION: sqlite
                DB_DATABASE: database/database.sqlite
              run: php artisan test

    deploy:
        needs: laravel-tests
        runs-on: ubuntu-latest

        steps:
            - name: Check SSH key present
              run: |
                    test -n "${{ secrets.SSH_PRIVATE_KEY }}" || { echo "SSH_PRIVATE_KEY is not set. Exiting."; exit 1; }
                    echo "SSH_PRIVATE_KEY present"
            - name: Write SSH key to file
              run: |
                cat > key.pem <<'EOF'
                ${{ secrets.SSH_PRIVATE_KEY }}
                EOF
                chmod 600 key.pem

            - name: Fingerprint private key
              run: |
                ssh-keygen -y -f key.pem > key.pub
                ssh-keygen -l -E sha256 -f key.pub

            - name: Deploy to server
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  cd /var/www/Cars
                  git pull origin main
                  composer install --no-dev --optimize-autoloader
                  php artisan migrate --force
                  php artisan config:cache
                  php artisan route:cache
                  php artisan view:cache

                